# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e959c8100207c430d1409624f15925a677b02e3a997d349dda14d5c048a0b0a6b015b2e7fc355e40edee4728730eddf3b7ff6646ef97ec41b7dd72b47c3cb76

test:
  secret_key_base: 6ca01a72d3d498a3339abd165f3ac4c67f18d4c2146b7d5c6d9647efd96fe41584211b4f497355648748c60aea3e71beba47fb09362f025802d5fe03b2d18af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
